### ISSUE TITLE
#INC-5312: Missing image

### ISSUE THREAD

**Issue by vanessa-cooper** [ObelusFamily/Anythink-Market-bqumd#3]
It seems that when creating a new product without an image, there are broken images showing up in the product catalog. Please fix this by replicating this bug locally with mock data.
Take a screenshot of the fix and attach it to a PR when you close the bug. There's a placeholder image in the repo that you can use named `placeholder.png`

**Comment by iamdror** [comment]
- added mock image for when submitting an item without an image

![image](https://user-images.githubusercontent.com/93054042/168532750-69b3e882-e350-4d44-b774-4314a531d48c.png)
